services:
  api:
    image: mikaelle2rubia/picpay
    ports:
      - "8080:8080"
    depends_on:
      - db

  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"