CREATE TABLE IF NOT EXISTS public.users (
	balance numeric(38, 2) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cpf varchar(255) NULL,
	email varchar(255) NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	"password" varchar(255) NULL,
	usertype varchar(255) NULL,
	CONSTRAINT users_cpf_key UNIQUE (cpf),
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_usertype_check CHECK (((usertype)::text = ANY ((ARRAY['COMMON'::character varying, 'MERCHAN'::character varying])::text[])))
);