CREATE TABLE IF NOT EXISTS public.transactions (
	amount numeric(38, 2) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	receiver_id int8 NULL,
	sender_id int8 NULL,
	"timestamp" timestamp(6) NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (id)
);